# Generated by Django 4.2.17 on 2024-12-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dairy_app", "0004_alter_news_screen_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="screen_name",
            field=models.TextField(blank=True),
        ),
    ]
